#!/usr/bin/env python

import json
import requests
import sys
import uuid

server = 'http://172.24.4.1:18322'
auth_id = str(uuid.UUID(sys.argv[1], version=4))
response = requests.get(
    server + '/authorities/' + auth_id)
assert response.status_code == 200
auth = json.loads(response.content)
print auth
