#!/usr/bin/env python
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

import argparse
import json
import sys
import yaml

parser = argparse.ArgumentParser(
    description='Convert a single-line static vendor data file from'
                '\n{"cloud-init": <single-line cloud-config>}'
                '\nto multi-line cloud-config.',
    formatter_class=argparse.RawTextHelpFormatter
)
parser.add_argument('input_file', type=str)
args = parser.parse_args()

# load from file:
with open(args.input_file, 'r') as f:
    js = json.loads(f.read())

print js['cloud-init']
